import type { Metadata } from "next";
import { Molengo } from "next/font/google";
import "./globals.css";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";

import { ToastProvider } from "@/components/providers/toaster-provider";
import { extractRouterConfig } from "uploadthing/server";

import { ClerkProvider } from "@clerk/nextjs";
import { ourFileRouter } from "./api/uploadthing/core";

const inter = Molengo({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToastProvider />
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
